image: docker.siemens.com/code-ops/poetry-docker:1.1-py3.9

variables:
    http_proxy: $CODE_PROXY
    https_proxy: $CODE_PROXY
    no_proxy: code.siemens.com,docker.siemens.com
    POETRY_HTTP_BASIC_MKDOCS_USERNAME: gitlab-ci-token
    POETRY_HTTP_BASIC_MKDOCS_PASSWORD: $CI_JOB_TOKEN

# Fetch new commits from public repository
update:
    stage: build
    rules:
        - if: $CI_PIPELINE_SOURCE == "schedules"
    variables:
        PUBLIC_ORIGIN: "https://$MAINTAINER_GITHUB_ACCOUNT:$GITHUB_REPOSITORY_TOKEN@$PUBLIC_GITHUB_REPOSITORY"
    script:
        # Fetch branches from the remote public project
        - git remote add public $PUBLIC_ORIGIN
        - git fetch public
        - git branch -a
        - new_commit=$(git log origin/main..public/main | wc -l)
        - |
            if [ "${new_commit}" -gt 0 ]; then 
                echo "New commits where found on the remote master branch, build and deploy new website"
                git merge public/main
                git push -u origin main
            else:
                echo "No new commits where found on the remote master branch, exit pipeline"
            fi

# Deploy website
pages:
    stage: deploy
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    script:
        - poetry install --no-root -n
        - poetry run mkdocs build -d docs/
    artifacts:
        expire_in: 2d
        paths:
        - docs/
