variables:
    http_proxy: $CODE_PROXY
    https_proxy: $CODE_PROXY
    no_proxy: code.siemens.com,docker.siemens.com

pull_remote:
    variables:
        PUBLIC_ORIGIN: "https://deveaud-m:$GITHUB_REPOSITORY_TOKEN@github.com/deveaud-m/public-remote-test.git"
    script:
        - git remote add public $PUBLIC_ORIGIN
        - git remote -v
        - git branch -a
        - git fetch public
        - git log public/master