image: docker.siemens.com/code-ops/poetry-docker:1.1-py3.9

variables:
    http_proxy: $CODE_PROXY
    https_proxy: $CODE_PROXY
    no_proxy: code.siemens.com,docker.siemens.com
    POETRY_HTTP_BASIC_MKDOCS_USERNAME: gitlab-ci-token
    POETRY_HTTP_BASIC_MKDOCS_PASSWORD: $CI_JOB_TOKEN

stages:
    - fetch
    - build
    - deploy

update:
    stage: fetch
    rules:
        - if: $CI_PIPELINE_SOURCE == "schedule"
          allow_failure: true
    variables:
        PUBLIC_ORIGIN: "https://github.com/deveaud-m/public-remote-test.git"
    before_script:
        - git remote add public $PUBLIC_ORIGIN && git fetch public
        - if [ "$(git log origin/main..public/main | wc -l)" -eq 0 ]; then exit 1; fi
        - git checkout -b deploy public/main
    script:
        - echo "New commits where found on the remote main branch, build and deploy mkdocs"
        - poetry install --no-root -n
        - poetry run mkdocs build -d docs/
    artifacts:
        paths:
        - docs/

mkdocs:
    stage: build
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "schedule"
        - if: $CI_COMMIT_BRANCH == "deploy"
    script:
        - poetry install --no-root -n
        - poetry run mkdocs build -d docs/
    artifacts:
        paths:
        - docs/

pages:
  stage: deploy
  needs:
    - job: update
      artifacts: true
      optional: true
    - job: mkdocs
      artifacts: true
  script:
    - mv docs/ public/
  artifacts:
    paths:
      - public/
