image: docker.siemens.com/code-ops/poetry-docker:1.1-py3.9

variables:
    http_proxy: $CODE_PROXY
    https_proxy: $CODE_PROXY
    no_proxy: code.siemens.com,docker.siemens.com
    POETRY_HTTP_BASIC_MKDOCS_USERNAME: gitlab-ci-token
    POETRY_HTTP_BASIC_MKDOCS_PASSWORD: $CI_JOB_TOKEN

stages:
    - fetch
    - build
    - deploy

update:
    stage: fetch
    rules:
        - if: $CI_PIPELINE_SOURCE == "schedule"
          allow_failure: true
    variables:
        PUBLIC_ORIGIN: "https://github.com/deveaud-m/public-remote-test.git"
    before_script:
        - apt update && apt install -y openssh-client git
        - mkdir -p ~/.ssh/ && chmod 700 ~/.ssh
        - ssh-keyscan -H "code.siemens.com" > ~/.ssh/known_hosts
        - echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key && chmod 600 ~/.ssh/deploy_key
        - |
            cat <<EOF >> ~/.ssh/config
            Host $GITLAB_HOST
                User git
                Hostname $GITLAB_HOST
                IdentityFile ~/.ssh/deploy_key
                IdentitiesOnly yes
            EOF
    script:
        - git remote add public $PUBLIC_ORIGIN
        - git fetch public
        - new_commits=$(git log origin/main..public/main | wc -l)
        - |
            if [ "${new_commits}" -gt 0 ]; then
                echo "New commits where found on the remote main branch, build and deploy mkdocs"
                git checkout -b deploy public/main
                poetry install --no-root -n
                poetry run mkdocs build -d docs/
            else
                echo "No new commits where found on the remote master branch, exit pipeline"
                exit 1
            fi
    artifacts:
        paths:
        - docs/

build_pages:
    stage: build
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
        - if: $CI_COMMIT_BRANCH == "deploy"
        - if: $CI_PIPELINE_SOURCE == "schedule"
          when: never
    script:
        - poetry install --no-root -n
        - poetry run mkdocs build -d docs/
    artifacts:
        paths:
        - docs/

pages:
  stage: deploy
  script:
    - mv docs/ public/
  artifacts:
    paths:
      - public/
