variables:
    http_proxy: $CODE_PROXY
    https_proxy: $CODE_PROXY
    no_proxy: code.siemens.com,docker.siemens.com

pull_remote:
    variables:
        PUBLIC_ORIGIN: "https://deveaud-m:$GITHUB_REPOSITORY_TOKEN@github.com/deveaud-m/public-remote-test.git"
    before_script:
        - git config --global user.email "marion.deveaud@siemens.com"
        - git config --global user.name "Marion Deveaud"
    script:
        - git remote add public $PUBLIC_ORIGIN
        - git fetch public
        # Try to automatically merge commits from the public project into this project
        # If merge conflict arise, the job will fail 
        - git log origin/master..public/master && git merge public/master --allow-unrelated-histories
        - git log
        - git push origin HEAD:master -o skip.ci
