variables:
    http_proxy: $CODE_PROXY
    https_proxy: $CODE_PROXY
    no_proxy: code.siemens.com,docker.siemens.com

pull_remote:
    variables:
        PUBLIC_ORIGIN: "https://deveaud-m:$GITHUB_REPOSITORY_TOKEN@github.com/deveaud-m/public-remote-test.git"
    script:
        - git remote add public $PUBLIC_ORIGIN
        - git fetch public
        - git log origin/master..public/master && echo "New commits found in the public project"
